---
common:
  disable_legacy_facts: true
appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
.travis.yml:
  before_install_pre:
    - 'sudo add-apt-repository -y ppa:raphink/augeas'
    - 'sudo apt-get update'
    - 'sudo apt-get install augeas-tools augeas-lenses libaugeas0 libaugeas-dev libxml2-dev'
  notifications:
    email: true
  secure: 'kWnIvYSka7xUyIx44LQdzm9brxt8PcAZkrvDwcwYc7L6bgawm191xuPuneHvMgRSNQfatC/iui+jlLi0y6V8uDr6xojVKJHhI1R/D4vm/R3o3X0LBS9fzXZcFwasKSlvzWd3P6MPECEmDdjuHlydEUCjYKNDpCnmX8GXOWvpdrg5+ivP3FVOOHXUblHRzMvGkSYf0FUavtDpyPWVRBL3NVBvabHOgZjnseqfLYwE3InjEFYP93YgeKImtakT869hkgXGeU5EubTX8E+iUWoTiKZSy0He7HDZozQ/xelY5STxF6jNKXwgruOYjUpzivdIeJGDStApg8ks374EQYDDPJj3dFqbti9m+VpFTkfdqIoLiVDJ4+0RmAvuXDbYb5AxoBvKNElyro65luJqJIPjJhUztqFqNIVxh1R4jhHv1FVbFjsMwqUf+lBkujyaOj1U0PXq9oT8VQKZfX7Q8ClzegS0c9ReYv66nWEaO8zCg+Pc8q4qZqsd4j6W5aESxyxCCssVEbzIx0QzsA/OyxAyGWZzzHpF/MKZYCAX9yZ+nNfGFfz63g7CbjVwgATuUr3XW6t/VZmFZNPNVQ23ffj2aRhtAsU9NrrdQRndukfFmnqAh82FjeayJzP22pXLL9y2twmnIMO77/j3diWYJGRwgTwiNe3VHDJ8/VXq/ivDLiw='
  simplecov: true
  user: 'bodgit'
.vscode/extensions.json:
  delete: true
Gemfile:
  required:
    ':development':
      - gem: 'puppet-lint-absolute_classname-check'
      - gem: 'puppet-lint-alias-check'
      - gem: 'puppet-lint-empty_string-check'
      - gem: 'puppet-lint-file_ensure-check'
      - gem: 'puppet-lint-file_source_rights-check'
      - gem: 'puppet-lint-fileserver-check'
        git: 'https://github.com/bodgit/puppet-lint-fileserver-check.git'
        branch: 'puppet-lint-2.x'
      - gem: 'puppet-lint-leading_zero-check'
      - gem: 'puppet-lint-spaceship_operator_without_tag-check'
      - gem: 'puppet-lint-trailing_comma-check'
      - gem: 'puppet-lint-undef_in_function-check'
      - gem: 'puppet-lint-unquoted_string-check'
      - gem: 'puppet-lint-variable_contains_upcase'
      - gem: 'puppet-lint-version_comparison-check'
      - gem: 'ruby-augeas'
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        version: '~> 1.15'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.3.0')"
    ':system_tests':
      - gem: 'beaker-vagrant'
      - gem: 'beaker-rspec'
      - gem: 'beaker-puppet_install_helper'
      - gem: 'beaker-module_install_helper'
Rakefile:
  linter_fail_on_warnings: true
spec/spec_helper.rb:
  mock_with: ':mocha'
  coverage_report: true
  minimum_code_coverage_percentage: 100
