---
common:
  disable_legacy_facts: true
appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
.travis.yml:
  before_install_pre:
    - 'sudo add-apt-repository -y ppa:raphink/augeas'
    - 'sudo apt-get update'
    - 'sudo apt-get install augeas-tools augeas-lenses libaugeas0 libaugeas-dev libxml2-dev'
  notifications:
    email: true
  secure: 'PO+wr9xLKAe2w3p1GWmpPd9NDPnomGioX8yzchbKrr636SBPLiJ2K4irXb2Ox7ocer787egQxphiY4MjIQkRNv68oKiXIJXZAyRdfd0ySMtA9oh4K8/oXGLSmhN94DABDQgSZjkHO1fNcgpeAFN+KID8PNrXqatlnZJbVaYECqRscP1GyE9hqDHad0rY+FXSb9I5BvGAqw5tdO+4xiAFVBXE+0MgleJ3vNDDMh+VhrZ55seSYHDt1r463mmTiAppUMa0NZWzblMnfQ9gJMmOfE2zMu2Cm5W9zOKa7NwxoQ/CIBuc5b09lW532moXCcLBEpmd2jagPtS+JmfscpUEZW1q3SuOnYnr0sEVqEUvChBPx52SDjIPjZN+nGwAK8o66N7CbgCkQKcsg9PaR674ftcGIscdv63WObofDYDxEs5BU3ufPSwnL7XBNlnhsPxyKrhNIPRi1PkOqrwfVqhDbJNhV7vH0WbPLhQW2sFXY1PZ7uLXbuL/z5FOE1ocgEhTeVTQqN7zpJg3FQMyYPimOdRa9P3JmTkpN9eU7yKkg1xMYPq3Uu+VkPXeFfLX01jkkaPbowjqDEfSLi809zFUvAfiTKKg+Lp6dPwb4tuLS2OtfywdnwrNAnwhYQIq2aZOa5XVyYZ37yr+S7LU30Y0Lgqwn7W5jkhhAFgx2OApyeU='
  simplecov: true
  user: 'bodgit'
.vscode/extensions.json:
  delete: true
Gemfile:
  required:
    ':development':
      - gem: 'puppet-lint-absolute_classname-check'
      - gem: 'puppet-lint-alias-check'
      - gem: 'puppet-lint-empty_string-check'
      - gem: 'puppet-lint-file_ensure-check'
      - gem: 'puppet-lint-file_source_rights-check'
      - gem: 'puppet-lint-fileserver-check'
        git: 'https://github.com/bodgit/puppet-lint-fileserver-check.git'
        branch: 'puppet-lint-2.x'
      - gem: 'puppet-lint-leading_zero-check'
      - gem: 'puppet-lint-spaceship_operator_without_tag-check'
      - gem: 'puppet-lint-trailing_comma-check'
      - gem: 'puppet-lint-undef_in_function-check'
      - gem: 'puppet-lint-unquoted_string-check'
      - gem: 'puppet-lint-variable_contains_upcase'
      - gem: 'puppet-lint-version_comparison-check'
      - gem: 'ruby-augeas'
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        version: '~> 1.15'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.3.0')"
    ':system_tests':
      - gem: 'beaker-vagrant'
      - gem: 'beaker-rspec'
      - gem: 'beaker-puppet_install_helper'
      - gem: 'beaker-module_install_helper'
Rakefile:
  linter_fail_on_warnings: true
spec/spec_helper.rb:
  mock_with: ':mocha'
  coverage_report: true
  minimum_code_coverage_percentage: 100
